remove unused field from concord::daml::DataServiceImpl
GCC complained about this unused field, refusing to finish the build,
so I removed it.

In file included from blockchain/concord/src/daml/grpc_services.cpp:3:
blockchain/concord/src/daml/grpc_services.hpp:20:38: error: private field 'pool' is not used [-Werror,-Wunused-private-field]
  concord::consensus::KVBClientPool& pool;