Racetrack two sets per run (building phase separated)
- Updated the groovy file to have master failure notification to have
a few more useful info and links (suite name, case name, case history,
error message, error file and line number, link to error file, signature)

- Updated `racetrack` in groovy to have option for making `building` set
and `testing` set. (Every run will have two racetrack result sets: building
and testing). This is discerned by `forBuilding` flag on Hermes.

- Deleted `racetrack.groovy` and move it as `racetrackUpdate` on
groovy file. It takes `type` param (`building` | `testing`) and can
take `repo` variable (default `athena`) for future-proofing repo split.

- Removed `racetrackCaseFailed` and `racetrackCasePassed` in
`invoke.py` as they are no longer used to flag the building stage failure.
Also removed `reportFailure` call in `racetrack.groovy` for the same
reason.

- Added `replaceRunDescription`in `jenkins.py` which will replace the
`hidden HTML` section of the build description with active links as the
run progresses.

- Updated `setFailureSummaryInDescription` to have path check such
that the error messages of not finding `failure_summary.json` is no
longer polluting the Jenkins console (It was confusing people)

- Updated groovy file to have `racetrackUpdate` as the only way of
interacting  with Racetrack. (There was one instance of just `racetrack(`
which was throwing this error: `java.lang.NoSuchMethodError: No such
DSL method 'racetrack' found among steps`)

- Updated `racetrack.py` to have TWO set ids possible for the run
(`setId` and `buildSetId`). The `building` result set wil have `-build`
attached to the branch name to be distinguished from `testing` result
set on Racetrack.