Fix one clang error and two warnings
The error is about an unintialized variable. This variable is used to
verify the signature, and if it wasn't set properly, the signature
wasn't encoded properly. It's likely going to fail validation either
way, but setting it to zero is safe anyway. This was the error:

```
blockchain/concord/src/consensus/kvb_commands_handler.cpp:877:16: error: variable 'actualV' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
    } else if (chainID >= 27) {
               ^~~~~~~~~~~~~
blockchain/concord/src/consensus/kvb_commands_handler.cpp:936:45: note: uninitialized use occurs here
    *sender = verifier_.ecrecover(rlp_hash, actualV, sigR, sigS);
                                            ^~~~~~~
blockchain/concord/src/consensus/kvb_commands_handler.cpp:877:12: note: remove the 'if' if its condition is always true
    } else if (chainID >= 27) {
           ^~~~~~~~~~~~~~~~~~~
blockchain/concord/src/consensus/kvb_commands_handler.cpp:862:19: note: initialize the variable 'actualV' to silence this warning
    int8_t actualV;
                  ^
                   = '\0'
```

The warnings were in the tests:

```
blockchain/concord/test/time_contract_test.cpp:38:3: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
blockchain/concord/test/time_contract_test.cpp:90:3: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
blockchain/concord/test/replicaStateSync_test.cpp:54:3: warning: control reaches end of non-void function [-Wreturn-type]
  }
  ^
```